In [10]:
import pandas as pd
from pathlib import Path
import os

In [11]:
root_path = str(Path(os.path.abspath('')).parents[1])
event_info_path = os.path.join(root_path, 'data/data_transformed/event_info.csv')
result_values_path = os.path.join(root_path, 'data/data_transformed/result_values.csv')
result_units_path = os.path.join(root_path, 'data/data_transformed/result_units.csv')


event_info_df = pd.read_csv(event_info_path, sep=';')
result_values_df = pd.read_csv(result_values_path, sep=';', encoding='latin1')
result_units_df = pd.read_csv(result_units_path, sep=';')

event_info_df.head(10)

,year,competition_name,event_name,distance,time_limit,main_measurement_unit,second_measurement_unit,min_weight,max_weight,weights,deadlift,attempts,max_lifts,lifts_num,implements_num,implements
0,2002,Arnold Strongman Challenge,Apollon's Wheels,NaN,NaN,kg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2002,Arnold Strongman Challenge,Max Deadlift,NaN,NaN,kg,NaN,NaN,NaN,NaN,Standard bar,NaN,NaN,NaN,NaN,NaN
2,2002,Arnold Strongman Challenge,Hummer Push,12.0,NaN,s,m,3628.0,3628.0,[3628.0],NaN,NaN,NaN,NaN,NaN,NaN
3,2002,Arnold Strongman Challenge,Timber Carry,11.0,NaN,s,NaN,370.0,370.0,[370.0],NaN,NaN,NaN,NaN,NaN,NaN
4,2003,Arnold's Strength Summit,Apollon's Wheels,NaN,NaN,reps,NaN,166.0,166.0,[166.0],NaN,NaN,NaN,NaN,NaN,NaN
5,2003,Arnold's Strength Summit,Max Deadlift,NaN,NaN,kg,NaN,NaN,NaN,NaN,Hummer tires,NaN,NaN,NaN,NaN,NaN
6,2003,Arnold's Strength Summit,Medicine Ball Toss,NaN,NaN,m,NaN,23.0,23.0,[23.0],NaN,NaN,NaN,NaN,NaN,NaN
7,2003,Arnold's Strength Summit,Timber Carry,11.0,NaN,s,m,392.0,392.0,[392.0],NaN,NaN,NaN,NaN,NaN,NaN
8,2004,Arnold's Strongest Man,Apollon's Wheels,NaN,NaN,reps,NaN,166.0,166.0,[166.0],NaN,NaN,NaN,NaN,NaN,NaN
9,2004,Arnold's Strongest Man,Max Deadlift,NaN,NaN,kg,NaN,NaN,NaN,NaN,Hummer tires,NaN,NaN,NaN,NaN,NaN

In [12]:
event_info_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2342 entries, 0 to 2341
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   year                     2342 non-null   int64
 1   competition_name         2342 non-null   object
 2   event_name               2342 non-null   object
 3   distance                 629 non-null    float64
 4   time_limit               1481 non-null   float64
 5   main_measurement_unit    2191 non-null   object
 6   second_measurement_unit  1214 non-null   object
 7   min_weight               1954 non-null   float64
 8   max_weight               1954 non-null   float64
 9   weights                  1954 non-null   object
 10  deadlift                 135 non-null    object
 11  attempts                 14 non-null     float64
 12  max_lifts                923 non-null    float64
 13  lifts_num                0 non-null      float64
 14  implements_num           947 non-null    float64
 15  implements               433 non-null    object
dtypes: float64(8), int64(1), object(7)
memory usage: 292.9+ KB

In [13]:
event_info_filtered_df = event_info_df[event_info_df['event_name']=="Timber Carry"]
event_info_filtered_df.head(30)

,year,competition_name,event_name,distance,time_limit,main_measurement_unit,second_measurement_unit,min_weight,max_weight,weights,deadlift,attempts,max_lifts,lifts_num,implements_num,implements
3,2002,Arnold Strongman Challenge,Timber Carry,11.0,NaN,s,NaN,370.0,370.0,[370.0],NaN,NaN,NaN,NaN,NaN,NaN
7,2003,Arnold's Strength Summit,Timber Carry,11.0,NaN,s,m,392.0,392.0,[392.0],NaN,NaN,NaN,NaN,NaN,NaN
12,2004,Arnold's Strongest Man,Timber Carry,11.0,30.0,s,m,392.0,392.0,[392.0],NaN,NaN,NaN,NaN,NaN,NaN
18,2005,Arnold's Strongest Man,Timber Carry,11.0,NaN,m,NaN,392.0,392.0,[392.0],NaN,NaN,NaN,NaN,NaN,NaN
19,2006,Arnold Strongman Classic,Timber Carry,11.0,NaN,s,m,392.0,392.0,[392.0],NaN,NaN,NaN,NaN,NaN,NaN
25,2007,Arnold Strongman Classic,Timber Carry,11.0,NaN,s,m,392.0,392.0,[392.0],NaN,NaN,NaN,NaN,NaN,NaN
31,2008,Arnold Strongman Classic,Timber Carry,11.0,NaN,s,m,392.0,392.0,[392.0],NaN,NaN,NaN,NaN,NaN,NaN
37,2009,Arnold Strongman Classic,Timber Carry,11.0,NaN,s,m,392.0,392.0,[392.0],NaN,NaN,NaN,NaN,NaN,NaN
47,2010,Arnold Strongman Classic,Timber Carry,11.0,NaN,s,m,454.0,454.0,[454.0],NaN,NaN,NaN,NaN,NaN,NaN
51,2011,Arnold Strongman Classic,Timber Carry,11.0,NaN,s,m,476.0,476.0,[476.0],NaN,NaN,NaN,NaN,NaN,NaN
57,2012,Arnold Strongman Classic,Timber Carry,11.0,NaN,s,m,400.0,400.0,[400.0],NaN,NaN,NaN,NaN,NaN,NaN
64,2014,Arnold Strongman Classic,Timber Carry,11.0,NaN,s,m,400.0,400.0,[400.0],NaN,NaN,NaN,NaN,NaN,NaN
68,2015,Arnold Strongman Classic,Timber Carry,11.0,NaN,s,m,500.0,500.0,[500.0],NaN,NaN,NaN,NaN,NaN,NaN
76,2016,Arnold Strongman Classic,Timber Carry,11.0,NaN,s,m,500.0,500.0,[500.0],NaN,NaN,NaN,NaN,NaN,NaN
78,2017,Arnold Strongman Classic,Timber Carry,11.0,30.0,s,m,563.0,563.0,[563.0],NaN,NaN,NaN,NaN,NaN,NaN
84,2018,Arnold Strongman Classic,Timber Carry,11.0,NaN,s,m,400.0,400.0,[400.0],NaN,NaN,NaN,NaN,NaN,NaN
96,2020,Arnold Strongman Classic,Timber Carry,11.0,30.0,s,m,400.0,400.0,[400.0],NaN,NaN,NaN,NaN,NaN,NaN
101,2022,Arnold Strongman Classic,Timber Carry,10.0,30.0,s,m,400.0,400.0,[400.0],NaN,NaN,NaN,NaN,NaN,NaN
107,2023,Arnold Strongman Classic,Timber Carry,11.0,30.0,s,m,400.0,400.0,[400.0],NaN,NaN,NaN,NaN,NaN,NaN
109,2024,Arnold Strongman Classic,Timber Carry,11.0,30.0,s,m,400.0,400.0,[400.0],NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
result_values_df.describe()

,year,Apollon's Wheels,Max Deadlift,Hummer Push,Timber Carry,Medicine Ball Toss,Hammer Lift,Dumbbell Press,Weight Throw,Super Yoke,...,Circle of Strength,Loading Medley,Pickaxe Hold,Stone Off,Train Push,Wrecking Ball Hold,Deadlift Machine,Kettlebell Throw,Chain Railway Carriage,Axle Death-Lift
count,3071.000000,126.000000,727.000000,8.000000,196.000000,28.000000,20.000000,501.000000,56.000000,685.000000,...,24.000000,50.000000,50.000000,140.000000,20.000000,60.000000,30.000000,46.000000,10.000000,15.000000
mean,2012.642462,2.357143,362.374140,18.962500,7.699184,3.553214,14.637000,6.280878,4.135893,18.277985,...,353.666667,17.322000,27.411600,2.185714,35.215000,72.628000,5.733333,6.961304,33.178000,19.642667
std,7.033411,2.174265,141.115717,4.469266,5.431979,2.102138,9.134774,16.290828,1.787920,12.423294,...,182.770149,26.948483,14.077967,3.419339,12.340447,35.567851,1.257620,10.691730,6.686507,22.898441
min,1986.000000,0.000000,0.000000,10.820000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,42.000000,2.000000,0.000000,0.000000,0.000000,0.000000,4.000000,0.000000,25.340000,3.000000
25%,2008.000000,0.000000,363.000000,17.482500,3.677500,3.202500,5.000000,0.000000,4.300000,10.750000,...,231.000000,3.000000,23.250000,0.000000,36.310000,60.700000,5.000000,3.250000,29.120000,4.000000
50%,2014.000000,2.000000,400.000000,18.265000,7.385000,4.720000,16.900000,3.000000,4.600000,17.800000,...,360.000000,3.000000,30.640000,0.000000,37.680000,76.900000,5.000000,5.000000,31.555000,5.000000
75%,2018.000000,4.000000,436.000000,21.310000,10.375000,4.760000,20.255000,6.000000,4.925000,25.220000,...,508.000000,4.000000,35.390000,5.000000,41.190000,95.180000,6.750000,6.000000,35.250000,27.320000
max,2024.000000,8.000000,549.000000,25.600000,24.820000,5.180000,30.150000,130.000000,6.250000,71.100000,...,612.000000,87.190000,48.030000,11.000000,44.120000,140.490000,8.000000,53.220000,47.670000,79.000000

In [15]:
result_units_df.describe(include='all')

,year,competition_name,competitor,Apollon's Wheels,Max Deadlift,Hummer Push,Timber Carry,Medicine Ball Toss,Hammer Lift,Dumbbell Press,...,Circle of Strength,Loading Medley,Pickaxe Hold,Stone Off,Train Push,Wrecking Ball Hold,Deadlift Machine,Kettlebell Throw,Chain Railway Carriage,Axle Death-Lift
count,3071.000000,3071,3071,121,640,8,187,28,20,446,...,0.0,50,44,48,18,56,30,46,10,15
unique,NaN,40,375,2,1,2,3,2,3,3,...,NaN,2,1,1,1,1,1,2,2,2
top,NaN,WSM Final - group,B. Shaw,reps,kg,s,m,m,s,reps,...,NaN,m,s,stones,s,s,reps,reps,s,reps
freq,NaN,1306,88,95,640,7,107,21,14,426,...,NaN,32,44,48,18,56,30,43,9,9
mean,2012.642462,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,7.033411,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,1986.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,2008.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,2014.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,2018.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,2024.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
base_cols = ['year', 'competition_name', 'competitor']
result_units_filtered_df = result_units_df[base_cols+ ["Timber Carry"]]
result_units_filtered_df.head(30)

    year            competition_name       competitor Timber Carry
0   2002  Arnold Strongman Challenge         M. Henry            s
1   2002  Arnold Strongman Challenge       S. Karlsen            s
2   2002  Arnold Strongman Challenge       P. Pfister            s
3   2002  Arnold Strongman Challenge      M. Philippi            s
4   2002  Arnold Strongman Challenge     R. Bergmanis          NaN
5   2002  Arnold Strongman Challenge        A. Bolton            s
6   2002  Arnold Strongman Challenge    B. Gillingham          NaN
7   2002  Arnold Strongman Challenge    B. Schoonveld            s
8   2003    Arnold's Strength Summit     Å½. Savickas            s
9   2003    Arnold's Strength Summit       S. Karlsen            s
10  2003    Arnold's Strength Summit     R. Bergmanis            m
11  2003    Arnold's Strength Summit  M. Pudzianowski            m
12  2003    Arnold's Strength Summit         S. Kirit            m
13  2003    Arnold's Strength Summit       P. Pfister            m
14  2003    Arnold's Strength Summit       Z. SedmÃ­k            m
15  2003    Arnold's Strength Summit    B. Gillingham         reps
16  2004      Arnold's Strongest Man     Å½. Savickas            s
17  2004      Arnold's Strongest Man       S. Karlsen            m
18  2004      Arnold's Strongest Man     R. Bergmanis            m
19  2004      Arnold's Strongest Man      M. Philippi            m
20  2004      Arnold's Strongest Man  M. Pudzianowski            m
21  2004      Arnold's Strongest Man     V. Virastyuk            m
22  2004      Arnold's Strongest Man    B. Schoonveld            m
23  2004      Arnold's Strongest Man     A. Johansson            m
24  2004      Arnold's Strongest Man         S. Kirit            m
25  2004      Arnold's Strongest Man        I. Ã�rvai            m
26  2005      Arnold's Strongest Man     Å½. Savickas            m
27  2005      Arnold's Strongest Man     V. Virastyuk            m
28  2005      Arnold's Strongest Man          G. Ross            m
29  2005      Arnold's Strongest Man      M. Philippi            m

In [17]:
result_values_df.head(5)

,year,competition_name,competitor,Apollon's Wheels,Max Deadlift,Hummer Push,Timber Carry,Medicine Ball Toss,Hammer Lift,Dumbbell Press,...,Circle of Strength,Loading Medley,Pickaxe Hold,Stone Off,Train Push,Wrecking Ball Hold,Deadlift Machine,Kettlebell Throw,Chain Railway Carriage,Axle Death-Lift
0,2002,Arnold Strongman Challenge,M. Henry,3.0,401.0,20.59,10.19,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2002,Arnold Strongman Challenge,S. Karlsen,0.0,352.0,17.62,9.50,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2002,Arnold Strongman Challenge,P. Pfister,3.0,324.0,18.00,8.70,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2002,Arnold Strongman Challenge,M. Philippi,1.0,374.0,18.53,20.84,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2002,Arnold Strongman Challenge,R. Bergmanis,1.0,370.0,17.07,0.00,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
base_cols = ['year', 'competition_name', 'competitor']
event_name = 'Timber Carry'
unit = 's'
event_info_filter_col = 'max_weight'
all_cols = base_cols + [event_name] + ['unit'] + [event_info_filter_col]
result_values_filtered_df = result_values_df[base_cols + [event_name]]
result_values_filtered_df['unit']=result_units_df[event_name]
result_values_filtered_df = result_values_filtered_df.merge(event_info_df[event_info_df['event_name']=="Timber Carry"], on=['year', 'competition_name'], how='left')[all_cols]
# event_info_df[event_info_df['event_name']=="Timber Carry"]["max_weight"]
# result_values_filtered_df['weight']=

result_values_filtered_df = result_values_filtered_df[(result_values_filtered_df['unit']=='s') & (result_values_filtered_df['max_weight']==400)]
result_values_filtered_df = result_values_filtered_df.sort_values('Timber Carry')
result_values_filtered_df.head(30)

C:\Users\The God of Cringe\AppData\Local\Temp\ipykernel_21396\4169870953.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result_values_filtered_df['unit']=result_units_df[event_name]

,year,competition_name,competitor,Timber Carry,unit,max_weight
176,2020,Arnold Strongman Classic,M. Kieliszkowski,7.00,s,400.0
205,2024,Arnold Strongman Classic,M. Hooper,7.10,s,400.0
95,2012,Arnold Strongman Classic,M. Jenkins,7.42,s,400.0
96,2012,Arnold Strongman Classic,D. Poundstone,7.56,s,400.0
101,2012,Arnold Strongman Classic,L. Shahlaei,7.91,s,400.0
196,2023,Arnold Strongman Classic,M. Kieliszkowski,8.35,s,400.0
208,2024,Arnold Strongman Classic,H. BjÃÂ¶rnsson,8.40,s,400.0
190,2022,Arnold Strongman Classic,M. Boudreault,8.41,s,400.0
206,2024,Arnold Strongman Classic,M. Kieliszkowski,8.69,s,400.0
120,2014,Arnold Strongman Classic,J. Pritchett,8.85,s,400.0
103,2012,Arnold Strongman Classic,T. Ortmayer,9.38,s,400.0
161,2018,Arnold Strongman Classic,J. Pritchett,9.58,s,400.0
185,2022,Arnold Strongman Classic,M. Licis,10.03,s,400.0
156,2018,Arnold Strongman Classic,B. Shaw,10.03,s,400.0
182,2020,Arnold Strongman Classic,J. Pritchett,10.31,s,400.0
117,2014,Arnold Strongman Classic,M. Burke,10.74,s,400.0
155,2018,Arnold Strongman Classic,H. BjÃÂ¶rnsson,11.80,s,400.0
203,2023,Arnold Strongman Classic,K. Faires,13.31,s,400.0
98,2012,Arnold Strongman Classic,B. Shaw,14.06,s,400.0
195,2023,Arnold Strongman Classic,M. Hooper,14.61,s,400.0
212,2024,Arnold Strongman Classic,M. Licis,14.81,s,400.0
99,2012,Arnold Strongman Classic,M. Burke,16.25,s,400.0
177,2020,Arnold Strongman Classic,M. Licis,17.37,s,400.0
116,2014,Arnold Strongman Classic,B. Shaw,18.72,s,400.0